kind: Service
apiVersion: v1
metadata:
  name: mysql
  labels: 
    app.kubernetes.io/name: mysql
    app.kubernetes.io/app: mysql
spec:
  selector:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/app: mysql
  ports:
  - port: 3306
    targetPort: 3306
